name: build
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
      
    steps:
    - name: deps
      run: |
        sudo apt update
        # rmf_core and traffic_editor dependencies
        sudo apt-get install libeigen3-dev libccd-dev libfcl-dev libyaml-cpp-dev -y
        # rmf_schedule_visualizer dependencies
        sudo apt-get install ros-eloquent-rviz2 ros-eloquent-launch* libyaml-cpp-dev libwebsocketpp-dev \
        libboost-system-dev libboost-date-time-dev libboost-regex-dev libboost-random-dev -y
    - name: setup
      run: |
        cd /home/
        mkdir -p ws_rmf/src
        cd ws_rmf/src
        git clone https://github.com/osrf/traffic_editor
        git clone https://github.com/osrf/rmf_core
        git clone https://github.com/osrf/rmf_schedule_visualizer
    - name: checkout
      shell: bash
      run:  |
        cd /home/ws_rmf/src/rmf_schedule_visualizer
        git checkout "${GITHUB_REF:11}"
    - name: build
      shell: bash
      run: |
        cd /home/ws_rmf
        source /opt/ros/eloquent/setup.bash
        colcon build
